```python
[08-May-24 17:51] -> initializer.initializer -> [DEBUG]: The database already exists.
[08-May-24 17:51] -> connection -> [DEBUG]: Server listening on localhost:9999
[08-May-24 17:51] -> connection -> [DEBUG]: Connection from ('127.0.0.1', 64606)
[08-May-24 17:51] -> connection -> [DEBUG]: Received: 0 admin admin
[08-May-24 17:51] -> commands.client -> [DEBUG]: Client is authorized -> ID<1>, fullname: None
[08-May-24 17:51] -> connection -> [DEBUG]: Response: 0 0 1 None 2
[08-May-24 17:51] -> connection -> [DEBUG]: Received: 6
[08-May-24 17:51] -> connection -> [DEBUG]: Response: 6 0 1 1 1 1715165295.0 1|2 2 1 1715165305.0 2
[08-May-24 17:51] -> connection -> [DEBUG]: Received: 6
[08-May-24 17:51] -> connection -> [DEBUG]: Response: 6 0 3 3 1 1715165394.0 3
[08-May-24 17:51] -> connection -> [DEBUG]: Received: 20 [*] [None,3,None,1715165478.635998,2]
[08-May-24 17:51] -> connection -> [DEBUG]: Response: 20 0 4 3 2 1715165478.0 2
[08-May-24 17:51] -> connection -> [DEBUG]: Received: 6
[08-May-24 17:51] -> connection -> [DEBUG]: Response: 6 0 4 3 2 1715165478.0 2
[08-May-24 17:51] -> connection -> [DEBUG]: Client ('127.0.0.1', 64606) disconnected
